name: Deploy to Dev
on:
  push:
    branches:
    - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        ref: dev
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: rxostaging
        SRC_PATH: "wp-content/themes/rxo"
        REMOTE_PATH: "wp-content/themes/rxo"
        # Deploy Options
        CACHE_CLEAR: TRUE