name: Deploy to Production
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: rxoincstg
        # Deploy Options
        REMOTE_PATH: "wp-content/"
        CACHE_CLEAR: TRUE